'use strict';

/**
 * The bot catalogue (module 07). The bot is both a tool and an object of test:
 * its risk gate is a pure function tested without a chain, its operational
 * discipline is tested against a fresh anvil.
 *
 * Same shape as perpdex.cases.js and miniapi.cases.js; rendered by generate.js.
 * Order here fixes the IDs (230..), so it matches be-bot.feature's @case tags.
 */

const H = 'High', M = 'Medium', L = 'Low';

const RM = '07. BOT — risk gate';
const GM = '07. BOT — contract gates';
const LM = '07. BOT — lifecycle';
const FM = '07. BOT — fills';
const OM = '07. BOT — operations';

// A risk-gate case needs no chain; an operational case drives PerpDEX on anvil.
const unit = (o) => ({ tier: 'BE/BOT', bindTier: 'bot', run: 'Auto', priority: M, pre: 'none -- the risk engine is a pure function', ...o });
const chain = (o) => ({ tier: 'BE/BOT', bindTier: 'bot', run: 'Auto', priority: M, pre: 'anvil with a fresh PerpDEX; the bot drives one account', ...o });

const cases = [
  // ------------------------------------------------------------ risk gate (pure)
  unit({ key: 'bot.risk.round', module: RM, fn: 'RiskEngine.plan', priority: H,
    title: 'The risk gate rounds size to the step and price to the tick',
    purpose: 'The contract reverts on a bad tick or step; the gate makes the order legal where it safely can',
    steps: ['build a risk engine with the ETH spec (tick 0.01, step 0.001, min notional $10)', 'plan a buy of 1.2345 ETH at 2500.567 → expect action send, size floored to 1.234, price floored to 2500.56'],
    expected: 'Cleared to send, size and price floored' }),
  unit({ key: 'bot.risk.kill', module: RM, fn: 'RiskEngine.killSwitch', priority: H,
    title: 'The kill switch refuses every order',
    purpose: 'One flag must stop all trading, unconditionally',
    steps: ['engage the kill switch', 'plan any order → expect refused with reason "kill-switch"'],
    expected: 'Refused: kill-switch' }),
  unit({ key: 'bot.risk.maxorder', module: RM, fn: 'RiskEngine.maxOrderSize',
    title: 'An order above the max order size is refused',
    purpose: 'A fat-finger single order must not reach the chain',
    steps: ['max order size 5', 'plan a buy of 6 ETH → expect refused with reason "max-order-size"'],
    expected: 'Refused: max-order-size' }),
  unit({ key: 'bot.risk.maxpos', module: RM, fn: 'RiskEngine.maxPositionSize', priority: H,
    title: 'An order that would breach the max position is refused, but a reduce-only order is not',
    purpose: 'The cap bounds exposure; reducing exposure must always be allowed',
    steps: ['max position 10, existing position 7 ETH', 'plan a buy of 4 ETH → expect refused with reason "max-position"', 'plan a reduce-only sell of 4 ETH → expect cleared to send'],
    expected: 'Increase refused; reduce-only cleared' }),
  unit({ key: 'bot.risk.zero', module: RM, fn: 'RiskEngine.step',
    title: 'A size that rounds to zero at the step is refused',
    purpose: 'A size below one step would floor to nothing; sending it is a bug',
    steps: ['ETH step 0.001', 'plan a buy of 0.0005 ETH → expect refused with reason "zero-size"'],
    expected: 'Refused: zero-size' }),
  unit({ key: 'bot.risk.minnotional', module: RM, fn: 'RiskEngine.minNotional',
    title: 'An order below the minimum notional is refused',
    purpose: 'The gate catches this before the chain does, saving a reverted transaction',
    steps: ['ETH min notional $10', 'plan a buy of 0.001 ETH at 2500 ($2.50) → expect refused with reason "below-min-notional"'],
    expected: 'Refused: below-min-notional' }),
  unit({ key: 'bot.risk.dup', module: RM, fn: 'RiskEngine.idempotent', priority: H,
    title: 'A repeated userOrderId is a no-op, not a second order',
    purpose: 'A retried request must not place the order twice',
    steps: ['plan a buy with user order id 1 → expect send', 'plan the same with user order id 1 again → expect action duplicate'],
    expected: 'Second plan is a duplicate' }),
  unit({ key: 'bot.risk.dryrun', module: RM, fn: 'RiskEngine.dryRun',
    title: 'Dry run clears an order but does not send it',
    purpose: 'A dry run must validate exactly as a live run, and stop short of sending',
    steps: ['engage dry run', 'plan a valid buy → expect action dry-run'],
    expected: 'Cleared as a dry run' }),

  // ------------------------------------------------------------ contract gates (chain)
  chain({ key: 'bot.gate.postonly', module: GM, fn: 'placeOrder / PostOnlyWouldCross', priority: H,
    title: 'A post-only order that would cross is surfaced, not retried',
    purpose: 'A deterministic revert must be reported once, never looped on',
    steps: ['bob rests an ask at 2500', 'the bot places a post-only buy at 2500 → expect it reverts PostOnlyWouldCross', 'expect the bot attempted the place exactly once'],
    expected: 'PostOnlyWouldCross, one attempt' }),
  chain({ key: 'bot.gate.reduceonly', module: GM, fn: 'placeOrder / ReduceOnlyViolation',
    title: 'A reduce-only order with no position is surfaced',
    purpose: 'The gate allows reduce-only through; the contract must reject it when there is nothing to reduce',
    steps: ['the bot places a reduce-only sell with no position → expect it reverts ReduceOnlyViolation'],
    expected: 'ReduceOnlyViolation' }),
  chain({ key: 'bot.gate.band', module: GM, fn: 'placeOrder / PriceOutOfBand',
    title: 'A limit outside the band is surfaced',
    purpose: 'A price the risk gate does not bound is bounded by the contract',
    steps: ['the bot places a buy at 3000 while the index is 2500 (band 5%) → expect it reverts PriceOutOfBand'],
    expected: 'PriceOutOfBand' }),
  chain({ key: 'bot.gate.paused', module: GM, fn: 'placeOrder / MarketPaused',
    title: 'An order on a paused market is surfaced',
    purpose: 'Market status is enforced by the contract, and the bot reports it',
    steps: ['the admin sets ETH to Paused', 'the bot places a buy → expect it reverts MarketPaused'],
    expected: 'MarketPaused' }),
  chain({ key: 'bot.gate.settling', module: GM, fn: 'placeOrder / MarketSettling',
    title: 'An order on a settling market is surfaced',
    purpose: 'A settling market takes no new orders',
    steps: ['the admin sets ETH to Settling at 2500', 'the bot places a buy → expect it reverts MarketSettling'],
    expected: 'MarketSettling' }),
  chain({ key: 'bot.gate.selftrade', module: GM, fn: 'placeOrder / SelfTradePrevented', priority: H,
    title: 'The bot cannot cross its own resting order',
    purpose: 'An account trading with itself would be a wash; the contract prevents it',
    steps: ['the bot rests a buy at 2499', 'the bot places a sell at 2499 → expect it reverts SelfTradePrevented'],
    expected: 'SelfTradePrevented' }),

  // ------------------------------------------------------------ lifecycle (chain)
  chain({ key: 'bot.life.fund', module: LM, fn: 'fundTrader / initializeAccount',
    title: 'The bot funds and initialises an account',
    purpose: 'The bot must be able to stand up its own account from nothing',
    steps: ['fund the bot with $50000 → expect accountExists true and vault balance $50000'],
    expected: 'Account exists, balance $50000' }),
  chain({ key: 'bot.life.place', module: LM, fn: 'place / getOrder', priority: H,
    title: 'The bot places a limit and reads it back as planned',
    purpose: 'A placed order must be observable, with the risk-rounded values',
    steps: ['the bot places a limit buy of 1.2345 ETH at 2498.567 → read the order back → expect Open, size 1.234, price 2498.56'],
    expected: 'Open, rounded size and price' }),
  chain({ key: 'bot.life.cancel', module: LM, fn: 'cancelOrder',
    title: 'The bot cancels its order',
    purpose: 'A cancel must move the order to Cancelled and free the slot',
    steps: ['the bot rests a buy; cancel it → expect status Cancelled and 0 open orders'],
    expected: 'Cancelled, 0 open orders' }),
  chain({ key: 'bot.life.cancelall', module: LM, fn: 'cancelAll',
    title: 'Cancel-all clears every resting order',
    purpose: 'A bot must be able to withdraw fully in one call',
    steps: ['the bot rests three buys → expect 3 open orders', 'cancel all → expect 0 open orders'],
    expected: '3 then 0 open orders' }),
  chain({ key: 'bot.life.flatten', module: LM, fn: 'flatten', priority: H,
    title: 'Flatten returns the bot to a clean slate after a fill',
    purpose: 'The discipline every scenario relies on: end flat',
    steps: ['the bot rests an order and takes a position', 'flatten ETH → expect flat (position 0, 0 open orders)'],
    expected: 'Flat on ETH' }),
  chain({ key: 'bot.life.dryrun', module: LM, fn: 'place / dryRun',
    title: 'A dry-run bot plans an order but places nothing on chain',
    purpose: 'Dry run must not leave any state behind',
    steps: ['a dry-run bot plans a limit buy → expect cleared as a dry run and 0 open orders on chain'],
    expected: 'Dry run, nothing on chain' }),

  // ------------------------------------------------------------ fills (chain)
  chain({ key: 'bot.fill.backstop', module: FM, fn: 'place Market / OrderFilled', priority: H,
    title: 'A market buy fills against the backstop',
    purpose: 'On an empty book the market order must fall to the backstop and fill',
    steps: ['the bot buys 1 ETH at market → expect position 1 ETH and the backstop -1 ETH'],
    expected: 'Bot +1, backstop -1' }),
  chain({ key: 'bot.fill.partial', module: FM, fn: 'place IOC / partial',
    title: 'An IOC limit fills what it can and cancels the rest',
    purpose: 'IOC must take available liquidity and drop the remainder, not rest it',
    steps: ['bob rests an ask of 1 ETH at 2500', 'the bot places an IOC buy of 3 ETH at 2500 → expect position 1 ETH'],
    expected: 'Position 1 ETH' }),
  chain({ key: 'bot.fill.size', module: FM, fn: 'getPosition',
    title: 'A fill sets the position size and a positive entry price',
    purpose: 'A position must record both its size and where it was opened',
    steps: ['the bot buys 2 ETH at market → expect size 2 ETH and entry price above 0'],
    expected: 'Size 2, entry > 0' }),
  chain({ key: 'bot.fill.margin', module: FM, fn: 'freeCollateral',
    title: 'A fill debits free collateral for the margin',
    purpose: 'Opening a position must lock initial margin',
    steps: ['the bot buys 1 ETH at market → expect free collateral below the vault balance'],
    expected: 'Free collateral fell' }),
  chain({ key: 'bot.fill.fee', module: FM, fn: 'fee / treasury',
    title: 'A taker fill pays a fee to the treasury',
    purpose: 'A taker must pay, and the fee must reach the treasury',
    steps: ['note the treasury balance', 'the bot buys 1 ETH at market → expect the treasury balance to increase'],
    expected: 'Treasury balance increased' }),
  chain({ key: 'bot.fill.mined', module: FM, fn: 'receipt',
    title: 'A fill is mined and observable in the block it landed in',
    purpose: 'A fill must be a mined transaction, not a hopeful send',
    steps: ['the bot buys 1 ETH at market → expect the receipt status 0x1 with a block number, and position 1 ETH'],
    expected: 'Mined, position 1 ETH' }),

  // ------------------------------------------------------------ operations
  unit({ key: 'bot.ops.retry', module: OM, fn: 'withRetry', priority: H,
    title: 'The retry policy retries a transient failure but never a revert',
    purpose: 'Retrying a deterministic revert loops forever and hides the finding; retrying a transient recovers',
    steps: ['a transient (ChainUnreachable) is retried up to the limit (3 tries)', 'a Reverted is surfaced on the first attempt (1 try)'],
    expected: 'Transient retried, revert not' }),
  chain({ key: 'bot.ops.nonce', module: OM, fn: 'eth_getTransactionCount', priority: H,
    title: 'Three orders advance the account nonce by exactly three',
    purpose: 'Sequential nonces mean no dropped or duplicated sends',
    steps: ['the bot places three limits → expect the account nonce to advance by exactly 3, consecutively'],
    expected: 'Nonce advanced by 3' }),
  chain({ key: 'bot.ops.pause', module: OM, fn: 'placeOrder / ExchangePaused',
    title: 'The bot halts when the exchange is paused',
    purpose: 'A paused exchange must stop the bot, surfaced as ExchangePaused',
    steps: ['the admin pauses the exchange', 'the bot places a buy → expect it reverts ExchangePaused'],
    expected: 'ExchangePaused' }),
  chain({ key: 'bot.ops.cleanup', module: OM, fn: 'flatten', priority: H,
    title: 'Cleanup leaves the venue flat, confirmed by re-reading',
    purpose: 'Cleanup must be verified by reading state back, not assumed from receipts',
    steps: ['the bot rests an order and takes a position', 'flatten ETH → re-read → expect flat and 0 open orders'],
    expected: 'Flat, 0 open orders' }),
  unit({ key: 'bot.ops.nosecret', module: OM, fn: 'log', priority: H,
    title: 'The bot holds and logs no secret',
    purpose: 'On anvil the node signs; the bot must carry nothing secret to leak',
    steps: ['inspect the bot record and fields → expect no 64-hex-character secret and no private-key field'],
    expected: 'No secret anywhere' }),
  chain({ key: 'bot.ops.killswitch', module: OM, fn: 'killSwitch',
    title: 'Once the kill switch is thrown the bot sends nothing more',
    purpose: 'The kill switch must stop live sends, not just planning',
    steps: ['engage the bot kill switch', 'the bot places a buy → expect refused with reason "kill-switch" and 0 open orders on chain'],
    expected: 'Refused, nothing on chain' }),

  // ------------------------------------------------------------ parameterised over the three markets
  chain({ key: 'bot.param.btc', module: LM, fn: 'place (BTC)',
    title: 'BTC: the bot places a valid limit sized to clear the minimum notional',
    purpose: 'One invariant across markets: a correctly sized limit rests',
    steps: ['the bot places a limit buy of 0.01 BTC at 59000 → expect Open and notional >= min notional'],
    expected: 'Open, clears min notional' }),
  chain({ key: 'bot.param.eth', module: LM, fn: 'place (ETH)',
    title: 'ETH: the bot places a valid limit sized to clear the minimum notional',
    purpose: 'One invariant across markets: a correctly sized limit rests',
    steps: ['the bot places a limit buy of 0.1 ETH at 2490 → expect Open and notional >= min notional'],
    expected: 'Open, clears min notional' }),
  chain({ key: 'bot.param.sol', module: LM, fn: 'place (SOL)',
    title: 'SOL: the bot places a valid limit sized to clear the minimum notional',
    purpose: 'One invariant across markets: a correctly sized limit rests',
    steps: ['the bot places a limit buy of 1 SOL at 99 → expect Open and notional >= min notional'],
    expected: 'Open, clears min notional' }),
];

module.exports = { cases };
