'use strict';

/**
 * The mini-api catalogue: the DB tier (the indexer's SQLite, opened directly
 * by both test stacks) and the API tier (the REST layer over that store).
 *
 * Each case compares exactly ONE pair, so a divergence names one layer:
 *   chain <-> DB   -> the indexer          (module 05, tier `db`)
 *   DB    <-> API  -> the REST layer       (module 06, tier `api-mini`)
 *
 * Same shape as perpdex.cases.js; rendered by generate.js.
 */

const H = 'High', M = 'Medium', L = 'Low';

const db = (o) => ({ tier: 'BE/DB', bindTier: 'db', run: 'Auto', priority: M, pre: 'anvil with a fresh PerpDEX; mini-api running and its indexer caught up', ...o });
const api = (o) => ({ tier: 'BE/API', bindTier: 'api-mini', run: 'Auto', priority: M, pre: 'anvil with a fresh PerpDEX; mini-api running and its indexer caught up', ...o });

const DBM = '05. DB — indexer store';
const APIM = '06. API — mini-api over the store';
const MSEC = '08. API — authentication edges';

const cases = [
  // ------------------------------------------------------------ 05 DB: chain <-> store
  db({ key: 'db.schema', module: DBM, fn: 'schema.sql', priority: H,
    title: 'The store has the documented tables, and every event table is keyed by (tx_hash, log_index)',
    purpose: 'The schema is the contract between indexer, API and tests; a missing unique key is what lets duplicates in',
    steps: ['open the store read-only; read sqlite_master → expect tables indexer_state, markets, orders, trades, positions, position_events, funding, liquidations, accounts, index_prices, applied_logs, api_keys', 'read PRAGMA index_list for trades, funding, liquidations, position_events, applied_logs → expect a unique index over (tx_hash, log_index)'],
    expected: 'All tables present; event tables uniquely keyed' }),
  db({ key: 'db.constraints', module: DBM, fn: 'schema.sql', priority: H,
    title: 'Schema constraints refuse a zero-size trade, an unknown market, and a bad status',
    purpose: 'Constraints are the last line; they must actually be enforced, not just written',
    pre: 'A throwaway in-memory database with schema.sql applied and foreign keys on',
    steps: ['insert a trades row with size "0" → expect a CHECK failure', 'insert an orders row with market_id 99 → expect a FOREIGN KEY failure', 'insert a markets row with status "Weird" → expect a CHECK failure', 'insert the same trades (tx_hash, log_index) twice → expect the second to fail'],
    expected: 'Every bad row is refused' }),
  db({ key: 'db.state.follows', module: DBM, fn: 'indexer_state', priority: H,
    title: 'The store follows exactly the deployed exchange on chain 31337',
    purpose: 'A store pointed at the wrong deployment would compare against the wrong contract',
    steps: ['read indexer_state → expect exchange == deployments/31337.json exchange (case-insensitive), chain_id 31337, genesis_hash == eth_getBlockByNumber(0).hash'],
    expected: 'Exchange, chain and genesis all match' }),
  db({ key: 'db.state.lag', module: DBM, fn: 'indexer_state.last_block', priority: H,
    title: 'The indexer keeps up: last_block reaches the chain head within the poll interval',
    purpose: 'Lag is the first symptom of a dead indexer',
    steps: ['mine a block; wait up to 5 s → read indexer_state.last_block → expect == eth_blockNumber', 'read last_block_hash → expect == the hash of that block'],
    expected: 'last_block == head and its hash matches' }),
  db({ key: 'db.markets.seeded', module: DBM, fn: 'markets', priority: H,
    title: 'Market rows equal the contract getters',
    purpose: 'Markets are seeded from getters, not events; a drift here would mislabel every other row',
    steps: ['read markets → expect COUNT == marketCount()', 'for each row: symbol, status, tick_size, step_size, min_notional, max_leverage, maker/taker fee, max_basis_bps == getMarket / getMarketParams'],
    expected: 'Row for row equal' }),
  db({ key: 'db.index.price', module: DBM, fn: 'index_prices', priority: H,
    title: 'The stored index price follows the oracle',
    purpose: 'The API derives the mark from this row; a stale index mis-marks every position',
    steps: ['setMockPrice(ETH, 2600); wait for the block to be indexed → read index_prices where market_id = 1 → expect price 2600e8 and publish_time == the reading\'s'],
    expected: 'Row equals getIndexPrice' }),
  db({ key: 'db.trade.row', module: DBM, fn: 'trades', priority: H,
    title: 'One OrderFilled becomes exactly one trades row, keyed by its tx and log index',
    purpose: 'A fill missed or doubled is the indexer failing at its one job',
    steps: ['bob rests an ask; alice buys at market; read the receipt\'s OrderFilled (tx_hash, logIndex, size, price)', 'wait indexed → read trades where tx_hash and log_index match → expect exactly one row with size, price, taker, maker, taker_order_id, taker_fee equal to the event'],
    expected: 'Exactly one row, field for field' }),
  db({ key: 'db.trade.backstop', module: DBM, fn: 'trades', priority: H,
    title: 'A backstop fill is stored with the zero address as maker and maker_order_id 0',
    purpose: 'Readers tell venue liquidity from trader liquidity by this column',
    steps: ['alice buys at market on an empty book → wait indexed → read the trade → expect maker == 0x000…000 and maker_order_id == 0'],
    expected: 'Zero maker, zero maker order' }),
  db({ key: 'db.trade.fk', module: DBM, fn: 'trades → orders', priority: H,
    title: 'Every trade references an order the store knows',
    purpose: 'No orphan rows: a trade whose order is missing means an OrderPlaced was dropped',
    steps: ['after several fills → SELECT trades t LEFT JOIN orders o ON o.order_id = t.taker_order_id WHERE o.order_id IS NULL → expect 0 rows', 'same for maker_order_id <> 0'],
    expected: 'Zero orphans on both sides' }),
  db({ key: 'db.order.placed', module: DBM, fn: 'orders', priority: H,
    title: 'An OrderPlaced becomes an orders row equal to getOrder',
    purpose: 'The orders table is rebuilt from the event alone; every field must survive the trip',
    steps: ['alice rests a limit with userOrderId 77 → wait indexed → read orders where order_id → expect owner, market_id, side, order_type, tif, size, price, reduce_only, user_order_id, max_ts, status Open equal to getOrder'],
    expected: 'Row equals the getter' }),
  db({ key: 'db.order.filled', module: DBM, fn: 'orders.filled / status', priority: H,
    title: 'After a full fill the row shows filled == size and status Filled, like the chain',
    purpose: 'filled is accumulated from trades; the derived status must flip at exactly the full size',
    steps: ['bob rests 1 ETH; alice buys 1 ETH at market → wait indexed → read bob\'s order row → expect filled == size and status Filled; getOrder(bob).status == Filled'],
    expected: 'Row and getter agree' }),
  db({ key: 'db.order.cancelled', module: DBM, fn: 'orders.status', priority: M,
    title: 'A cancel is reflected as status Cancelled',
    purpose: 'Open-order views must not show cancelled orders',
    steps: ['alice rests then cancels → wait indexed → read the row → expect status Cancelled'],
    expected: 'Cancelled' }),
  db({ key: 'db.position.matches', module: DBM, fn: 'positions', priority: H,
    title: 'The positions row equals getPosition for size and entry price',
    purpose: 'Positions are the most-read table and the easiest to drift: they are rebuilt from PositionChanged',
    steps: ['alice buys 2 ETH then sells 0.5 → wait indexed → read positions (alice, 1) → expect size 1.5e8 and entry_price == getPosition.entryPrice'],
    expected: 'Row equals the getter' }),
  db({ key: 'db.position.realized', module: DBM, fn: 'positions.realized_pnl', priority: M,
    title: 'Lifetime realised PnL in the store equals the contract\'s',
    purpose: 'Summed from event deltas; a double-applied event shows up here first',
    steps: ['open, then partially close at a profit → wait indexed → read positions.realized_pnl → expect == getPosition.realizedPnl'],
    expected: 'Sums agree' }),
  db({ key: 'db.position.sum', module: DBM, fn: 'positions', priority: H,
    title: 'Per market, long sizes equal short sizes, and both equal the contract\'s open interest',
    purpose: 'Every long has a short; the backstop counts. A mismatch is a lost or duplicated PositionChanged',
    steps: ['after fills on each market → SELECT SUM(size>0), SUM(-size where size<0) per market → expect equal, and each == getMarket().openInterestLong/Short'],
    expected: 'Balanced and equal to chain OI' }),
  db({ key: 'db.position_events.pair', module: DBM, fn: 'position_events', priority: M,
    title: 'One fill writes two position_events rows: taker and maker (backstop included)',
    purpose: 'The event pair is what the positions table is derived from',
    steps: ['alice buys at market against the backstop → wait indexed → read position_events for that tx → expect 2 rows: alice and the backstop address, with sizeAfter of opposite sign'],
    expected: 'Two rows, opposite signs' }),
  db({ key: 'db.funding.row', module: DBM, fn: 'funding', priority: M,
    title: 'A FundingUpdated across a boundary becomes a funding row equal to getFundingRate',
    purpose: 'Funding history is served from here',
    steps: ['advance the clock one interval; updateFunding → wait indexed → read funding newest for market 1 → expect rate_bps == lastRateBps, cumulative_index == cumulativeIndex, funding_time == lastFundingTime'],
    expected: 'Row equals the getter' }),
  db({ key: 'db.liquidation.row', module: DBM, fn: 'liquidations', priority: H,
    title: 'A liquidation becomes a liquidations row equal to the Liquidated event',
    purpose: 'Liquidations are the rows people dispute; every field must be exact',
    steps: ['thin long; crash the index; keeper liquidates → wait indexed → read the row by tx → expect account, liquidator, size_closed, price, liquidator_fee, bad_debt, insurance_used == the event'],
    expected: 'Field for field' }),
  db({ key: 'db.accounts.flow', module: DBM, fn: 'accounts', priority: L,
    title: 'Deposits and withdrawals accumulate on the accounts row',
    purpose: 'The portfolio summary reads these sums',
    steps: ['fund alice $1000; withdraw $250 → wait indexed → read accounts(alice) → expect deposits 1000e6, withdrawals 250e6'],
    expected: 'Sums equal the events' }),
  db({ key: 'db.replay.idempotent', module: DBM, fn: 'applied_logs', priority: H,
    title: 'Replaying an already-indexed range changes nothing',
    purpose: 'Idempotence is what makes the indexer safe to restart and to rewind',
    steps: ['note COUNT(*) of trades, orders, position_events, positions.size for alice', 'POST /admin/indexer {rewind: last_block - 10} → wait for last_block to return to head', 'read the same counts and values → expect identical'],
    expected: 'No row added, no value changed' }),
  db({ key: 'db.pause.freeze', module: DBM, fn: 'indexer_state.paused', priority: H,
    title: 'A paused indexer freezes the store while the chain moves on',
    purpose: 'The dangerous failure: rows that look fine and are old',
    steps: ['POST /admin/indexer {paused:true}; alice buys at market; wait 2 s → read indexer_state.last_block → expect unchanged and < eth_blockNumber; trades count unchanged', 'unpause; wait → expect last_block == head and the trade present'],
    expected: 'Frozen while paused, caught up after' }),
  db({ key: 'db.reorg.rebuild', module: DBM, fn: 'sync()', priority: H,
    title: 'After the chain reverts, the store rebuilds and matches the chain again',
    purpose: 'Rows from blocks that no longer exist must not survive',
    steps: ['snapshot; alice buys at market; wait indexed → trades count n+1', 'evm_revert to the snapshot; wait → expect indexer_state.rebuilds +1, last_block == head, trades count back to n, positions(alice) == getPosition (flat)'],
    expected: 'Store equals chain after the revert' }),
  db({ key: 'db.second_exchange', module: DBM, fn: 'indexer address filter', priority: H,
    title: 'Events from a second PerpDEX at another address are invisible to the store',
    purpose: 'The store follows one deployment; look-alike events from another must not leak in',
    pre: 'contracts built (forge build) so the PerpExchange bytecode is available',
    steps: ['deploy a second PerpExchange with the same vault/oracle; grace initialises an account on it → wait indexed → read accounts(grace) → expect no row; indexer_state.exchange unchanged'],
    expected: 'Nothing from the second deployment' }),
  db({ key: 'db.mark.ETH', module: DBM, fn: 'mark derivation', priority: H,
    title: 'ETH: mark derived from store rows equals getMarkPrice',
    purpose: 'The API\'s mark is clamp(last trade, index ± maxBasis) from rows; it must equal the contract\'s',
    steps: ['fill above index so the mark is off the index → wait indexed → compute clamp(trades.last.price, index_prices ± markets.max_basis_bps) → expect == getMarkPrice(1)'],
    expected: 'Derived == chain' }),
  db({ key: 'db.mark.BTC', module: DBM, fn: 'mark derivation', priority: M,
    title: 'BTC: mark derived from store rows equals getMarkPrice',
    purpose: 'Same rule, another market',
    steps: ['as ETH, on market 0'],
    expected: 'Derived == chain' }),
  db({ key: 'db.mark.SOL', module: DBM, fn: 'mark derivation', priority: M,
    title: 'SOL: mark derived from store rows equals getMarkPrice',
    purpose: 'Same rule, another market',
    steps: ['as ETH, on market 2'],
    expected: 'Derived == chain' }),

  // ------------------------------------------------------------ 06 API: store <-> REST
  api({ key: 'api.health', module: APIM, fn: 'GET /health', priority: H,
    title: '/health reports the store\'s indexer state',
    purpose: 'The one endpoint a monitor needs',
    steps: ['GET /health → expect 200, ok true, exchange == indexer_state.exchange, last_block == indexer_state.last_block, indexer_paused false, age_seconds small'],
    expected: 'Equal to the row' }),
  api({ key: 'api.markets.list', module: APIM, fn: 'GET /markets', priority: H,
    title: '/markets returns one entry per markets row with the row\'s fields',
    purpose: 'DB ↔ API on the most basic table',
    steps: ['GET /markets → expect markets.length == COUNT(markets); for each: symbol, status, tick_size, step_size, min_notional, max_leverage, fees, max_basis_bps == row; index_price == index_prices row'],
    expected: 'Row for row' }),
  api({ key: 'api.markets.one', module: APIM, fn: 'GET /markets/:id', priority: M,
    title: '/markets/1 returns the ETH row',
    purpose: 'Single-resource route',
    steps: ['GET /markets/1 → expect 200 and the same object as the list entry'],
    expected: 'Equal' }),
  api({ key: 'api.markets.mark', module: APIM, fn: 'GET /markets/:id', priority: H,
    title: 'mark_price in /markets equals the mark derived from the rows',
    purpose: 'The API derives; the test derives independently; they must agree',
    steps: ['after a fill → GET /markets/1 mark_price → expect == clamp(last trade, index ± max_basis) computed from the rows'],
    expected: 'Equal' }),
  api({ key: 'api.markets.oi', module: APIM, fn: 'GET /markets/:id', priority: M,
    title: 'open_interest_long/short in /markets equal the positions sums',
    purpose: 'Aggregates must come from the rows',
    steps: ['GET /markets/1 → expect open_interest_long == SUM(positive sizes), short == SUM(negative)'],
    expected: 'Equal' }),
  api({ key: 'api.markets.404', module: APIM, fn: 'GET /markets/:id', priority: M,
    title: 'An unknown market is 404 with the standard error shape',
    purpose: 'Errors are data too',
    steps: ['GET /markets/99 → expect 404, body {error, code: "not_found"}', 'GET /markets/abc → expect 404, same shape'],
    expected: '404 with {error, code}' }),
  api({ key: 'api.markets.status', module: APIM, fn: 'GET /markets/:id/status', priority: M,
    title: '/markets/:id/status follows a status change',
    purpose: 'Admin status changes reach the API through the store',
    steps: ['admin sets ETH Paused → wait indexed → GET /markets/1/status → expect status Paused == markets row', 'set Active back → expect Active'],
    expected: 'Follows the row' }),
  api({ key: 'api.orderbook.levels', module: APIM, fn: 'GET /orderbook/:id', priority: H,
    title: '/orderbook aggregates the store\'s open orders per price',
    purpose: 'Depth = SUM(size − filled) grouped by price, best first',
    steps: ['rest three bids at two prices → wait indexed → GET /orderbook/1 → expect bids sorted descending, each size == SUM over open orders at that price, orders count right'],
    expected: 'Equal to the aggregation' }),
  api({ key: 'api.orderbook.depth', module: APIM, fn: 'GET /orderbook/:id', priority: L,
    title: 'depth is validated',
    purpose: 'Bad input is 400, not a 500 or an empty list',
    steps: ['?depth=0 → 400; ?depth=51 → 400; ?depth=x → 400'],
    expected: '400 with {error, code: "bad_request"}' }),
  api({ key: 'api.orders.open', module: APIM, fn: 'GET /orders/:account', priority: H,
    title: '/orders/:account returns the account\'s Open rows by default',
    purpose: 'DB ↔ API on orders',
    steps: ['alice rests two limits, one cancelled → wait indexed → GET /orders/alice → expect exactly the rows with status Open'],
    expected: 'Equal' }),
  api({ key: 'api.orders.filter', module: APIM, fn: 'GET /orders/:account', priority: M,
    title: '?status=Cancelled and ?status=all select the right rows',
    purpose: 'Filters map to the column',
    steps: ['GET /orders/alice?status=Cancelled → expect the cancelled rows only; ?status=all → expect COUNT(orders where owner)'],
    expected: 'Equal' }),
  api({ key: 'api.orders.badaddr', module: APIM, fn: 'GET /orders/:account', priority: L,
    title: 'A malformed account is 400',
    purpose: 'Input validation',
    steps: ['GET /orders/not-an-address → 400 bad_request', 'GET /orders/0x1234?status=Weird → 400 bad_request'],
    expected: '400' }),
  api({ key: 'api.positions', module: APIM, fn: 'GET /positions/:account', priority: H,
    title: '/positions/:account returns the account\'s rows',
    purpose: 'DB ↔ API on positions',
    steps: ['GET /positions/alice → expect rows equal to SELECT * FROM positions WHERE account'],
    expected: 'Equal' }),
  api({ key: 'api.trades.total', module: APIM, fn: 'GET /trades', priority: H,
    title: '/trades total equals COUNT(trades)',
    purpose: 'total is the whole set, not the page',
    steps: ['GET /trades?limit=2 → expect total == COUNT(*) and trades.length == 2'],
    expected: 'Equal' }),
  api({ key: 'api.trades.order', module: APIM, fn: 'GET /trades', priority: M,
    title: '/trades is newest first by (block, log)',
    purpose: 'Ordering contract',
    steps: ['GET /trades → expect each row ≥ the next by (block_number, log_index)'],
    expected: 'Descending' }),
  api({ key: 'api.trades.cursor', module: APIM, fn: 'GET /trades', priority: H,
    title: 'Paging with the cursor yields every row exactly once',
    purpose: 'Keyset pagination correctness',
    steps: ['walk /trades?limit=2 following next_cursor until null → expect the union == all rows, no (tx, log) twice, next_cursor null at the end'],
    expected: 'Complete, no duplicates' }),
  api({ key: 'api.trades.limitcap', module: APIM, fn: 'GET /trades', priority: L,
    title: 'limit is capped at 100 and reported',
    purpose: 'A client cannot ask for the whole table',
    steps: ['GET /trades?limit=1000 → expect limit 100 in the body'],
    expected: 'Capped' }),
  api({ key: 'api.trades.badparams', module: APIM, fn: 'GET /trades', priority: L,
    title: 'Bad limit or cursor is 400',
    purpose: 'Input validation',
    steps: ['?limit=0 → 400; ?limit=abc → 400; ?cursor=%%% → 400'],
    expected: '400' }),
  api({ key: 'api.trades.market', module: APIM, fn: 'GET /trades', priority: M,
    title: '?market filters and total follows the filter',
    purpose: 'Filter correctness',
    steps: ['GET /trades?market=1 → expect every row market_id 1 and total == COUNT(trades where market_id = 1)', '?market=99 → 404'],
    expected: 'Filtered and counted' }),
  api({ key: 'api.funding.history', module: APIM, fn: 'GET /funding/history', priority: M,
    title: '/funding/history returns the funding rows for the market',
    purpose: 'DB ↔ API on funding',
    steps: ['advance one interval; updateFunding → wait indexed → GET /funding/history?market=1&period=1d → expect rows equal to the funding table for market 1'],
    expected: 'Equal' }),
  api({ key: 'api.funding.period', module: APIM, fn: 'GET /funding/history', priority: H,
    title: 'An unsupported period is 400 and the response lists the supported ones',
    purpose: 'A lenient endpoint that returns 200 for a period it does not understand is the worse bug',
    steps: ['?market=1&period=1h → 200; ?period=8h → 200; ?period=2h → 400 with supported ["1h","8h","1d"]; ?period=x → 400'],
    expected: '400 for anything but the three' }),
  api({ key: 'api.funding.market', module: APIM, fn: 'GET /funding/history', priority: L,
    title: 'market is required',
    purpose: 'Input validation',
    steps: ['GET /funding/history → 400 bad_request'],
    expected: '400' }),
  api({ key: 'api.liquidations', module: APIM, fn: 'GET /liquidations', priority: H,
    title: '/liquidations returns the liquidations rows',
    purpose: 'DB ↔ API on liquidations',
    steps: ['after a liquidation → GET /liquidations → expect total == COUNT and the newest row == the DB row'],
    expected: 'Equal' }),
  api({ key: 'api.portfolio.401', module: APIM, fn: 'GET /portfolio/summary', priority: H,
    title: 'No token is 401',
    purpose: 'Private data',
    steps: ['GET /portfolio/summary → 401 unauthenticated'],
    expected: '401' }),
  api({ key: 'api.portfolio.401.unknown', module: APIM, fn: 'GET /portfolio/summary', priority: H,
    title: 'An unknown token is 401',
    purpose: 'A made-up token must not be treated as read-scope',
    steps: ['Authorization: Bearer nope → 401 unauthenticated'],
    expected: '401' }),
  api({ key: 'api.portfolio.403.scope', module: APIM, fn: 'GET /portfolio/summary', priority: H,
    title: 'A read-scope token is 403',
    purpose: 'Scope is enforced, not just presence',
    steps: ['mint a read token via /auth/token → GET /portfolio/summary → 403 forbidden'],
    expected: '403' }),
  api({ key: 'api.portfolio.403.other', module: APIM, fn: 'GET /portfolio/summary', priority: H,
    title: 'A portfolio token bound to alice cannot read bob',
    purpose: 'Subject binding',
    steps: ['mint a portfolio token with subject alice → GET /portfolio/summary?account=bob → 403 forbidden'],
    expected: '403' }),
  api({ key: 'api.portfolio.ok', module: APIM, fn: 'GET /portfolio/summary', priority: H,
    title: 'A portfolio token returns exactly the documented fields, equal to the rows',
    purpose: 'DB ↔ API on the private view, and the field set is closed: nothing beyond account, exists, deposits, withdrawals, open_orders, positions',
    steps: ['mint a portfolio token for alice → GET /portfolio/summary → 200; keys == {account, exists, deposits, withdrawals, open_orders, positions}; values == accounts row, COUNT(open+pending orders), positions rows'],
    expected: 'Closed field set, equal to rows' }),
  api({ key: 'api.portfolio.expired', module: APIM, fn: 'GET /portfolio/summary', priority: M,
    title: 'An expired token is 401 token_expired',
    purpose: 'TTL enforcement',
    steps: ['mint a portfolio token with ttl 1 → wait 2 s → GET → 401 code token_expired'],
    expected: '401 token_expired' }),
  api({ key: 'api.auth.admin', module: APIM, fn: 'POST /auth/token', priority: H,
    title: 'Only an admin token can mint tokens',
    purpose: 'Privilege escalation guard',
    steps: ['POST /auth/token with a read token → 403; with no token → 401; with admin → 201 and a token row appears in api_keys'],
    expected: '403 / 401 / 201' }),
  api({ key: 'api.auth.badscope', module: APIM, fn: 'POST /auth/token', priority: L,
    title: 'An unknown scope or a malformed subject is 400',
    purpose: 'Input validation',
    steps: ['{scope: "root"} → 400; {scope: "read", subject: "x"} → 400'],
    expected: '400' }),
  api({ key: 'api.cors.allowed', module: APIM, fn: 'CORS', priority: H,
    title: 'An allowlisted origin is echoed back exactly, with credentials',
    purpose: 'The positive control for the six negatives below',
    steps: ['GET /markets with Origin: https://app.example.test → expect Access-Control-Allow-Origin == that exact string and Allow-Credentials true'],
    expected: 'Exact echo' }),
  api({ key: 'api.cors.suffix', module: APIM, fn: 'CORS', priority: H,
    title: 'A suffix attack origin gets no CORS header',
    purpose: 'https://app.example.test.evil.com must not match',
    steps: ['Origin: https://app.example.test.evil.com → expect no Access-Control-Allow-Origin'],
    expected: 'No header' }),
  api({ key: 'api.cors.parent', module: APIM, fn: 'CORS', priority: H,
    title: 'The parent domain gets no CORS header',
    purpose: 'https://example.test is not https://app.example.test',
    steps: ['Origin: https://example.test → expect no Access-Control-Allow-Origin'],
    expected: 'No header' }),
  api({ key: 'api.cors.scheme', module: APIM, fn: 'CORS', priority: H,
    title: 'The same host over http gets no CORS header',
    purpose: 'Scheme is part of the origin',
    steps: ['Origin: http://app.example.test → expect no Access-Control-Allow-Origin'],
    expected: 'No header' }),
  api({ key: 'api.cors.port', module: APIM, fn: 'CORS', priority: M,
    title: 'An explicit :443 gets no CORS header',
    purpose: 'Exact string match, no normalisation',
    steps: ['Origin: https://app.example.test:443 → expect no Access-Control-Allow-Origin'],
    expected: 'No header' }),
  api({ key: 'api.cors.null', module: APIM, fn: 'CORS', priority: M,
    title: '"null" and a missing Origin get no CORS header',
    purpose: 'null must not be allowlisted; a request with no Origin is not cross-origin and gets nothing -- which is correct, not a misconfiguration',
    steps: ['Origin: null → expect no ACAO', 'no Origin header → expect no ACAO and a normal 200'],
    expected: 'No header in both' }),
  api({ key: 'api.cors.preflight', module: APIM, fn: 'CORS', priority: M,
    title: 'Preflight from an allowed origin is 204 with methods and headers',
    purpose: 'Browsers need the preflight to succeed',
    steps: ['OPTIONS /portfolio/summary with Origin allowed and Access-Control-Request-Method GET → expect 204, Allow-Methods contains GET, Allow-Headers contains Authorization'],
    expected: '204 with the headers' }),
  api({ key: 'api.ratelimit', module: APIM, fn: 'rate limit', priority: H,
    title: 'Over the limit the API answers 429 with Retry-After',
    purpose: 'A limiter that silently drops or returns 200 is worse than none',
    steps: ['send limit+5 requests inside the window → expect the last ones 429, body code rate_limited, Retry-After header a positive integer, and X-RateLimit-Remaining 0 before the first 429'],
    expected: '429 + Retry-After' }),
  api({ key: 'api.stale.200', module: APIM, fn: 'indexer paused', priority: H,
    title: 'With the indexer paused the API keeps answering 200 with stale rows, and says so in /health',
    purpose: 'The failure that looks like health: the store is frozen, the API is fine, only the block number and the age give it away',
    steps: ['pause indexer; alice buys at market; wait 2 s → GET /trades total unchanged, status 200, X-Indexed-Block unchanged; GET /health indexer_paused true and age_seconds growing', 'unpause → total +1'],
    expected: '200 with stale data while paused; /health reveals it' }),

  // ------------------------------------------------------------ 08 API: authentication edges (secret hygiene)
  api({ key: 'api.security.malformed', bindTier: 'api-security', module: MSEC, fn: 'Authorization header', priority: H,
    title: 'A malformed Authorization header (no Bearer scheme) is 401',
    purpose: 'The token check must key on the Bearer scheme, not merely on some header being present',
    steps: ['GET /portfolio/summary?account=<any> with header "Authorization: Token k_whatever" (no Bearer scheme) → 401 unauthenticated'],
    expected: '401 unauthenticated' }),
  api({ key: 'api.security.hygiene', bindTier: 'api-security', module: MSEC, fn: 'secret hygiene', priority: M,
    title: 'Public responses never carry a bearer token',
    purpose: 'A minted token is returned once at /auth/token and must never echo back in ordinary reads',
    steps: ['GET /markets → the JSON body contains no "k_" bearer token', 'GET /health → the JSON body contains no "k_" bearer token'],
    expected: 'No credential in the response bodies' }),
];

module.exports = { cases };
