'use strict';

/**
 * The PerpDEX test-case catalogue, as data.
 *
 * This is the single source. `node testcases/generate.js` renders it three ways:
 *   PerpDEX-TestCases.md     for reading on GitHub
 *   PerpDEX-TestCases.xlsx   the tabular form QA teams exchange
 *   ../fixtures/testcases.json   what the automation binds to (IDs 43+)
 *
 * IDs are allocated by `key` on first generation and never reallocated: a key
 * that already has an ID keeps it, a new key gets nextId. Renaming a key is
 * the same as deleting a case and adding another, and is meant to be.
 *
 * Columns follow the usual QA sheet: Module · Function · Tier · Title · Purpose
 * · Precondition · Steps · Expected · Priority · Run. "Steps" name the function
 * called, the field read and the value expected -- concrete enough that a
 * reader can prove the check touched the right thing.
 */

const MARKETS = [
  { sym: 'BTC', id: 0, index: '60000', tick: '0.01', step: '0.0001', minNotional: '10', lev: 50, im: '2 %', mm: '1 %' },
  { sym: 'ETH', id: 1, index: '2500', tick: '0.01', step: '0.001', minNotional: '10', lev: 50, im: '2 %', mm: '1 %' },
  { sym: 'SOL', id: 2, index: '100', tick: '0.001', step: '0.01', minNotional: '10', lev: 20, im: '5 %', mm: '2.5 %' },
];

const T = 'BE/Contract';
const H = 'High', M = 'Medium', L = 'Low';

/** @param {object} c  { key, module, fn, title, purpose, pre, steps[], expected, priority } */
const c = (o) => ({ tier: T, run: 'Auto', priority: M, pre: 'Venue deployed on anvil; account initialised and funded unless stated', ...o });

const cases = [
  // ------------------------------------------------------------ 01 accounts & collateral
  c({ key: 'acct.init', module: '01. Accounts & collateral', fn: 'initializeAccount', priority: H,
    title: 'An account can be initialised exactly once',
    purpose: 'Every other call keys on account existence; a second init must not reset anything',
    pre: 'Fresh address, no account',
    steps: ['call initializeAccount() → expect event AccountInitialized(account)', 'call accountExists(account) → expect true', 'call initializeAccount() again → expect revert AccountExists()'],
    expected: 'First call succeeds and emits; second reverts AccountExists; getAccount(account).createdAt equals the first block timestamp' }),
  c({ key: 'acct.deposit.requires', module: '01. Accounts & collateral', fn: 'deposit', priority: H,
    title: 'Deposit before initialisation is rejected',
    purpose: 'AccountNotFound must gate every mutating call, deposit included',
    pre: 'Address with USDC and approval, no account',
    steps: ['approve(vault, 100) then call deposit(100) → expect revert AccountNotFound()'],
    expected: 'Revert AccountNotFound; vault.balanceOf(account) stays 0' }),
  c({ key: 'acct.deposit.ledger', module: '01. Accounts & collateral', fn: 'deposit', priority: H,
    title: 'Deposit moves tokens into the vault and credits the ledger by the same amount',
    purpose: 'Tokens held and ledger recorded are two records that must agree',
    steps: ['read vault.reserves() → (held0, ledger0)', 'call deposit(1000e6) → expect event Deposited(account, 1000e6)', 'read vault.balanceOf(account) → expect +1000e6', 'read vault.reserves() → expect held and ledger both +1000e6'],
    expected: 'held == ledger before and after; account balance +1000e6' }),
  c({ key: 'acct.withdraw.free', module: '01. Accounts & collateral', fn: 'withdraw', priority: H,
    title: 'Withdrawal is capped at free collateral',
    purpose: 'Collateral locked behind open positions must not leave the vault',
    pre: 'Account with $1000 and a 1 ETH long at index',
    steps: ['read freeCollateral(account) → f', 'call withdraw(f + 1) → expect revert InsufficientCollateral(f, f+1)', 'call withdraw(f) → expect success', 'read freeCollateral(account) → expect ≤ 0'],
    expected: 'Exactly the free amount is withdrawable, one unit more is refused' }),
  c({ key: 'acct.withdraw.negative', module: '01. Accounts & collateral', fn: 'withdraw',
    title: 'An account below zero can withdraw nothing',
    purpose: 'Bad debt must not be extractable',
    pre: 'Account liquidated into negative balance with the insurance fund empty',
    steps: ['read vault.balanceOf(account) → expect < 0', 'call withdraw(1) → expect revert InsufficientCollateral'],
    expected: 'Revert; balance unchanged' }),
  c({ key: 'acct.zero', module: '01. Accounts & collateral', fn: 'deposit/withdraw', priority: L,
    title: 'Zero-amount deposit and withdrawal are rejected',
    purpose: 'A zero movement would emit an event that means nothing',
    steps: ['call deposit(0) → expect revert ZeroAmount()', 'call withdraw(0) → expect revert ZeroAmount()'],
    expected: 'Both revert ZeroAmount' }),
  c({ key: 'acct.vault.only', module: '01. Accounts & collateral', fn: 'CollateralVault', priority: H,
    title: 'Only the exchange may move vault balances',
    purpose: 'The vault does bookkeeping; the exchange decides what is safe. No other caller may bypass that',
    pre: 'Any external address',
    steps: ['call vault.transferBetween(a, b, 1, "x") from a stranger → expect revert NotExchange()', 'call vault.withdrawFor(a, a, 1) from a stranger → expect revert NotExchange()'],
    expected: 'Both revert NotExchange' }),
  c({ key: 'acct.getter', module: '01. Accounts & collateral', fn: 'getAccount', priority: L,
    title: 'getAccount reports existence, open orders and creation time',
    purpose: 'The account record is what a UI and an indexer read; each field must reflect state',
    steps: ['call getAccount(account) → expect exists true, openOrders 0, createdAt == block.timestamp of init', 'place a resting limit → call getAccount → expect openOrders 1'],
    expected: 'Fields track state exactly' }),

  // ------------------------------------------------------------ 02 markets & status
  c({ key: 'mkt.add', module: '02. Markets & status', fn: 'addMarket', priority: H,
    title: 'Admin adds a market and it is immediately Active',
    purpose: 'Market creation is the root of every other test',
    pre: 'Admin key',
    steps: ['call addMarket("LINK-PERP", params) → expect returned id == marketCount before', 'read getMarket(id).status → expect Active', 'read getMarket(id).lastFundingTime → expect a multiple of fundingIntervalSec'],
    expected: 'id sequential; status Active; funding clock aligned to the interval' }),
  c({ key: 'mkt.add.notadmin', module: '02. Markets & status', fn: 'addMarket', priority: H,
    title: 'A non-admin cannot add a market',
    purpose: 'Admin surface must be closed',
    pre: 'Non-admin key',
    steps: ['call addMarket(...) → expect revert NotAdmin()'],
    expected: 'Revert NotAdmin; marketCount unchanged' }),
  c({ key: 'mkt.params.validate', module: '02. Markets & status', fn: 'addMarket / setMarketParams', priority: H,
    title: 'Parameters that cannot work together are refused',
    purpose: 'A market whose maintenance ≥ initial margin, or whose leverage exceeds what the margin supports, would misbehave silently',
    pre: 'Admin key',
    steps: ['params with maintenanceMarginBps == initialMarginBps → expect revert BadParams("maintenanceMarginBps")', 'params with initialMarginBps 200 and maxLeverage 100 → expect revert InvalidLeverage()', 'params with takerFeeBps 501 → expect revert BadParams("takerFeeBps")', 'params with makerFeeBps < -takerFeeBps → expect revert BadParams("makerFeeBps")'],
    expected: 'Each invalid combination reverts with the named reason' }),
  c({ key: 'mkt.cap', module: '02. Markets & status', fn: 'addMarket', priority: L,
    title: 'The market count is capped',
    purpose: 'Per-account loops iterate every market; the cap bounds that cost',
    pre: 'Admin key',
    steps: ['add markets until marketCount == MAX_MARKETS', 'call addMarket once more → expect revert TooManyMarkets()'],
    expected: 'Revert at the cap' }),
  c({ key: 'mkt.status.paused', module: '02. Markets & status', fn: 'setMarketStatus', priority: H,
    title: 'A Paused market rejects every new order, including reducing ones',
    purpose: 'Pause means no fills at all, not "no risk-increasing fills"',
    pre: 'Account with an open long on the market',
    steps: ['call setMarketStatus(m, Paused, 0)', 'place a reducing market sell → expect revert MarketPaused(m)', 'call cancelOrder on a resting order → expect success'],
    expected: 'Orders revert; cancels still work' }),
  c({ key: 'mkt.status.reduceonly', module: '02. Markets & status', fn: 'setMarketStatus', priority: H,
    title: 'A ReduceOnly market accepts only orders that shrink a position',
    purpose: 'Wind-down mode: no new risk',
    pre: 'Account long 2 units',
    steps: ['call setMarketStatus(m, ReduceOnly, 0)', 'place buy 1 → expect revert ReduceOnlyViolation()', 'place sell 3 (would flip) → expect revert ReduceOnlyViolation()', 'place sell 1 → expect fill; read getPosition → size 1'],
    expected: 'Growing and flipping orders revert; shrinking order fills' }),
  c({ key: 'mkt.status.settling', module: '02. Markets & status', fn: 'setMarketStatus', priority: H,
    title: 'Settling requires a settlement price and rejects orders',
    purpose: 'A market being closed must have one price everyone settles at',
    pre: 'Admin key',
    steps: ['call setMarketStatus(m, Settling, 0) → expect revert BadParams("settlementPrice")', 'call setMarketStatus(m, Settling, 2600e8) → expect event MarketStatusChanged', 'place any order → expect revert MarketSettling(m)'],
    expected: 'Zero price refused; orders refused once Settling' }),
  c({ key: 'mkt.settle.position', module: '02. Markets & status', fn: 'settlePosition', priority: H,
    title: 'Anyone can settle a position at the settlement price',
    purpose: 'Settlement is permissionless so a market can be closed without every holder acting',
    pre: 'Market Settling at 2600; alice long 1 from 2500, bob short 1 from 2500',
    steps: ['call settlePosition(alice, m) from a keeper → read getPosition(alice).size → expect 0; realizedPnl +100e6', 'call settlePosition(bob, m) → realizedPnl -100e6', 'call settlePosition(alice, m) again → expect revert NoPosition()'],
    expected: 'Both sides closed at 2600 with opposite PnL; second settle reverts' }),
  c({ key: 'mkt.settle.notsettling', module: '02. Markets & status', fn: 'settlePosition',
    title: 'settlePosition on an Active market reverts',
    purpose: 'Settlement must not be usable as a free close',
    pre: 'Active market with a position',
    steps: ['call settlePosition(account, m) → expect revert MarketNotSettling(m)'],
    expected: 'Revert' }),
  c({ key: 'mkt.getter', module: '02. Markets & status', fn: 'getMarket / getMarketParams', priority: L,
    title: 'Market getters return the configured parameters unchanged',
    purpose: 'What was set is what is read; a decimal slip here would be silent',
    steps: ['call getMarketParams(m) → compare every field with the params passed to addMarket'],
    expected: 'All sixteen fields equal' }),

  // ------------------------------------------------------------ 03 order types × time in force
  c({ key: 'ord.market.fill', module: '03. Order types × TIF', fn: 'placeOrder(Market)', priority: H,
    title: 'A market order fills immediately at the best available price',
    purpose: 'Market = take now; price is whatever the book (or backstop) offers',
    steps: ['place Market buy 1 on an empty book → read getOrder(id).status → expect Filled', 'read getPosition.entryPrice → expect index × (1 + backstopSpread)'],
    expected: 'Filled in the same call, at the backstop ask' }),
  c({ key: 'ord.market.remainder', module: '03. Order types × TIF', fn: 'placeOrder(Market)', priority: H,
    title: 'A market order larger than available liquidity fills what it can and cancels the rest',
    purpose: 'Market orders never rest',
    steps: ['place Market buy of backstopMaxSize + 50 on an empty book', 'read getOrder(id).filled → expect backstopMaxSize; status Cancelled', 'expect event OrderCancelled(reason "unfilled")'],
    expected: 'Partial fill then Cancelled, never Open' }),
  c({ key: 'ord.limit.rest', module: '03. Order types × TIF', fn: 'placeOrder(Limit, GTC)', priority: H,
    title: 'A GTC limit that does not cross rests on the book',
    purpose: 'Resting is what makes a book',
    steps: ['place Limit buy 1 at index × 0.96 → read getOrder(id).status → expect Open', 'call getOrderBook(m, 5) → expect a bid level at that price with source 0'],
    expected: 'Open, visible on the book' }),
  c({ key: 'ord.limit.cross', module: '03. Order types × TIF', fn: 'placeOrder(Limit, GTC)', priority: H,
    title: 'A limit that crosses fills at the resting price, not its own',
    purpose: 'Price improvement goes to the taker',
    pre: 'Resting ask at P',
    steps: ['place Limit buy at P + 20 ticks → read getPosition.entryPrice → expect P'],
    expected: 'Entry == resting price' }),
  c({ key: 'ord.limit.partial.rest', module: '03. Order types × TIF', fn: 'placeOrder(Limit, GTC)',
    title: 'A GTC limit partially filled rests for the remainder',
    purpose: 'GTC keeps working after a partial fill',
    pre: 'Resting ask 1 at P',
    steps: ['place Limit buy 3 at P → read getOrder(id) → expect filled 1, status Open, size 3'],
    expected: 'Remainder 2 rests' }),
  c({ key: 'ord.ioc', module: '03. Order types × TIF', fn: 'placeOrder(Limit, IOC)', priority: H,
    title: 'IOC fills what crosses and cancels the remainder',
    purpose: 'IOC never rests',
    pre: 'Resting ask 1 at P; backstop ask above P',
    steps: ['place Limit IOC buy 3 at P → read getOrder(id) → expect filled 1, status Cancelled', 'read getAccount.openOrders → expect 0'],
    expected: 'Partial fill, remainder cancelled, no slot held' }),
  c({ key: 'ord.fok.reject', module: '03. Order types × TIF', fn: 'placeOrder(Limit, FOK)', priority: H,
    title: 'FOK reverts when the full size cannot be filled, taking nothing',
    purpose: 'All-or-nothing must not leave a partial behind',
    pre: 'Resting ask 1 at P; backstop ask above P',
    steps: ['place Limit FOK buy 2 at P → expect revert FillOrKillUnfillable(1, 2)', 'read the resting ask → expect filled 0'],
    expected: 'Revert; resting order untouched' }),
  c({ key: 'ord.fok.fill', module: '03. Order types × TIF', fn: 'placeOrder(Limit, FOK)',
    title: 'FOK fills completely when liquidity suffices',
    purpose: 'The positive side of all-or-nothing',
    pre: 'Resting ask 1 at P',
    steps: ['place Limit FOK buy 1 at P → read getOrder(id).status → expect Filled'],
    expected: 'Filled' }),
  c({ key: 'ord.fok.backstop', module: '03. Order types × TIF', fn: 'placeOrder(Limit, FOK)',
    title: 'FOK counts the backstop when the limit reaches its quote',
    purpose: 'The backstop is liquidity; FOK must see it',
    steps: ['place Limit FOK buy 50 at index × (1 + spread) + 1 tick on an empty book → expect Filled at the backstop ask'],
    expected: 'Filled against the backstop' }),
  c({ key: 'ord.postonly.rest', module: '03. Order types × TIF', fn: 'placeOrder(Limit, PostOnly)', priority: H,
    title: 'PostOnly rests when it does not cross',
    purpose: 'Maker-only orders that make',
    steps: ['place PostOnly buy at index × 0.996 (inside the backstop spread) → expect status Open'],
    expected: 'Open' }),
  c({ key: 'ord.postonly.cross', module: '03. Order types × TIF', fn: 'placeOrder(Limit, PostOnly)', priority: H,
    title: 'PostOnly that would cross is rejected with the best opposite price',
    purpose: 'A maker-only order must never take; the error tells the client where the touch is',
    pre: 'Resting ask at P above the backstop ask B',
    steps: ['place PostOnly buy at P → expect revert PostOnlyWouldCross(P, B) — B is the better of book and backstop'],
    expected: 'Revert names the backstop price when it is better than the book' }),
  c({ key: 'ord.stop.park', module: '03. Order types × TIF', fn: 'placeOrder(StopMarket)', priority: H,
    title: 'A stop order parks as Pending and holds a slot without executing',
    purpose: 'Trigger orders wait; they must not touch the position',
    steps: ['place StopMarket buy trigger index + 100 → read getOrder(id).status → expect Pending', 'read pendingTriggerIds(m) → contains id', 'read getPosition.size → expect 0; getAccount.openOrders → 1'],
    expected: 'Pending, slot taken, no fill' }),
  c({ key: 'ord.stop.trigger', module: '03. Order types × TIF', fn: 'triggerOrder', priority: H,
    title: 'A keeper triggers a stop once the source price crosses it',
    purpose: 'Permissionless triggering is the keeper role',
    pre: 'Pending buy-stop at T on the Index source',
    steps: ['call triggerOrder(id) with index < T → expect revert TriggerNotMet(T, index)', 'setMockPrice(m, T)', 'call triggerOrder(id) from any address → expect event OrderTriggered; status Filled; position size +1'],
    expected: 'Refused below trigger, executes at/above' }),
  c({ key: 'ord.stoplimit', module: '03. Order types × TIF', fn: 'placeOrder(StopLimit)',
    title: 'A stop-limit becomes a limit at its price after triggering',
    purpose: 'Stop-limit = trigger then limit, not trigger then market',
    steps: ['place StopLimit buy trigger T, limit T + 10 → setMockPrice(T) → triggerOrder(id)', 'read entryPrice → expect the backstop ask at T (below the limit), not the limit itself'],
    expected: 'Fills at the best price ≤ limit' }),
  c({ key: 'ord.takeprofit', module: '03. Order types × TIF', fn: 'placeOrder(TakeProfit)',
    title: 'Take-profit triggers in the opposite direction to a stop',
    purpose: 'Sell TP fires when price RISES to the trigger; a sell stop fires when it FALLS',
    pre: 'Long 1; TakeProfit sell reduceOnly at index + 100',
    steps: ['triggerOrder(id) at index → expect revert TriggerNotMet', 'setMockPrice(index + 100) → triggerOrder(id) → position size 0'],
    expected: 'Fires upward, closes the long' }),
  c({ key: 'ord.trigger.source', module: '03. Order types × TIF', fn: 'triggerOrder', priority: H,
    title: 'Mark and Index trigger sources are distinct',
    purpose: 'Mark can differ from index by the basis; a client chooses which one fires the stop',
    pre: 'Last fill above index so mark > index',
    steps: ['place two buy-stops at a trigger between index and mark: one Mark-sourced, one Index-sourced', 'triggerOrder(markOne) → expect success', 'triggerOrder(indexOne) → expect revert TriggerNotMet'],
    expected: 'Only the Mark-sourced order fires' }),
  c({ key: 'ord.maxts', module: '03. Order types × TIF', fn: 'placeOrder', priority: H,
    title: 'maxTs is compared to the chain clock in microseconds, and equality is not expiry',
    purpose: 'Clients that use wall-clock seconds get silently wrong behaviour; the unit is documented by this test',
    steps: ['read clockMicros() → c', 'place with maxTs = c - 1 → expect revert OrderExpired(c-1, c)', 'place with maxTs = c → expect success'],
    expected: 'Strictly-less is expired; equal is live' }),

  // ------------------------------------------------------------ 04 book & matching
  c({ key: 'book.priority', module: '04. Book & matching', fn: 'matching', priority: H,
    title: 'Price priority, then time priority',
    purpose: 'The core promise of a book',
    pre: 'Asks: A at P (first), B at P+1, C at P (later)',
    steps: ['place Market buy 1.5 → expect A Filled, C filled 0.5, B filled 0'],
    expected: 'Best price first; within a price, earlier first' }),
  c({ key: 'book.levels', module: '04. Book & matching', fn: 'getOrderBook',
    title: 'getOrderBook aggregates same-price orders into one level',
    purpose: 'A depth view, not an order list',
    pre: 'Two asks at P of 1 each',
    steps: ['call getOrderBook(m, 5) → expect one ask level at P with size 2'],
    expected: 'Aggregated' }),
  c({ key: 'book.backstop.level', module: '04. Book & matching', fn: 'getOrderBook', priority: H,
    title: 'The backstop appears on both sides of the book with source 1',
    purpose: 'A reader must be able to tell venue liquidity from trader liquidity',
    steps: ['call getOrderBook(m, 5) on an empty book → expect one bid at index × (1 − spread) and one ask at index × (1 + spread), both source 1, size backstopMaxSize'],
    expected: 'Two backstop levels, source 1' }),
  c({ key: 'book.backstop.best', module: '04. Book & matching', fn: 'matching', priority: H,
    title: 'A better book price is taken before the backstop, and the backstop fills the rest',
    purpose: 'The backstop is last resort, not first',
    pre: 'Resting ask 1 at P below the backstop ask',
    steps: ['place Market buy 2 → expect entry = blended (P, backstopAsk); resting order Filled; backstop position −1'],
    expected: 'Book first, then backstop' }),
  c({ key: 'book.backstop.unfunded', module: '04. Book & matching', fn: 'matching',
    title: 'An unfunded backstop does not quote',
    purpose: 'The backstop quotes only what it can settle',
    pre: 'Backstop drained to zero',
    steps: ['call getOrderBook(m, 5) → expect no source-1 levels', 'place Market buy 1 on an empty book → expect status Cancelled, filled 0'],
    expected: 'No backstop liquidity' }),
  c({ key: 'book.selftrade', module: '04. Book & matching', fn: 'matching', priority: H,
    title: 'Self-trade is prevented',
    purpose: 'An account matching itself would fake volume and fees',
    pre: 'Own resting ask at P',
    steps: ['place own Limit buy at P → expect revert SelfTradePrevented(restingId)'],
    expected: 'Revert naming the resting order' }),
  c({ key: 'book.cancel', module: '04. Book & matching', fn: 'cancelOrder', priority: H,
    title: 'Cancel removes the order from the book and frees the slot',
    purpose: 'A cancelled order must vanish from every view',
    steps: ['place resting limit → cancelOrder(id) → expect event OrderCancelled(reason "user")', 'read getOrder(id).status → Cancelled; getAccount.openOrders → 0; getOrderBook → level gone'],
    expected: 'Gone from status, count and book' }),
  c({ key: 'book.cancel.owner', module: '04. Book & matching', fn: 'cancelOrder', priority: H,
    title: 'Only the owner can cancel',
    purpose: 'Otherwise anyone could clear the book',
    steps: ['cancelOrder(id) from another account → expect revert NotOrderOwner()'],
    expected: 'Revert' }),
  c({ key: 'book.cancelall', module: '04. Book & matching', fn: 'cancelAll',
    title: 'cancelAll is scoped by market, or all markets with the sentinel',
    purpose: 'Kill-switch semantics',
    pre: 'Two resting orders on ETH, one on BTC',
    steps: ['cancelAll(ETH) → expect return 2; openOrders 1', 'cancelAll(0xFFFF) → expect return 1; openOrders 0'],
    expected: 'Counts and remaining slots match' }),

  // ------------------------------------------------------------ 05 positions
  c({ key: 'pos.blend', module: '05. Positions', fn: 'position', priority: H,
    title: 'Adding to a position blends the entry by volume',
    purpose: 'Average entry is what PnL is computed from',
    steps: ['buy 1 at 2500, buy 1 at 2501 → read getPosition → size 2, entryPrice 2500.50'],
    expected: 'Volume-weighted entry' }),
  c({ key: 'pos.reduce', module: '05. Positions', fn: 'position', priority: H,
    title: 'Reducing realises PnL at the fill price and leaves the entry unchanged',
    purpose: 'Partial close arithmetic',
    steps: ['long 2 at 2500; sell 1 at 2502 → read getPosition → size 1, entryPrice 2500, realizedPnl +2e6', 'read balance delta → +2e6 − taker fee'],
    expected: 'Entry kept; realised +2; balance moved by pnl − fee' }),
  c({ key: 'pos.flip', module: '05. Positions', fn: 'position', priority: H,
    title: 'A fill larger than the position flips it, closing at the old entry and opening at the fill',
    purpose: 'Netting through zero',
    steps: ['long 1 at 2500; sell 3 at 2498 → read getPosition → size −2, entryPrice 2498, realizedPnl −2e6'],
    expected: 'Closed 1 for −2, new short 2 at 2498' }),
  c({ key: 'pos.flat', module: '05. Positions', fn: 'position',
    title: 'Closing to flat clears the entry and removes the holder',
    purpose: 'A flat position must not leave stale state for ADL ranking',
    steps: ['long 1; sell 1 → read getPosition → size 0, entryPrice 0', 'read holdersOf(m) → does not contain the account'],
    expected: 'Clean flat' }),
  c({ key: 'pos.upnl', module: '05. Positions', fn: 'equity', priority: H,
    title: 'Unrealised PnL in equity follows the mark, not the index',
    purpose: 'Equity is marked at the mark; the difference matters exactly when the basis is non-zero',
    steps: ['long 1 at 2500 (mark 2500); setMockPrice(2600) → mark clamps to 2574', 'read equity delta → expect +74e6, not +100e6'],
    expected: 'Equity moves by the clamped mark' }),
  c({ key: 'pos.oi', module: '05. Positions', fn: 'getMarket', priority: H,
    title: 'Open interest is tracked on both sides and always equal',
    purpose: 'Every long has a short; a drift would mean a lost position',
    steps: ['after any fills read getMarket(m).openInterestLong and openInterestShort → expect equal', 'after a reduce → both decreased by the closed size'],
    expected: 'Long OI == short OI at every step' }),
  c({ key: 'pos.estliq', module: '05. Positions', fn: 'estimatedLiquidationPrice', priority: L,
    title: 'Estimated liquidation price sits below entry for a long and above for a short',
    purpose: 'The figure a UI shows must at least point the right way',
    steps: ['long 1 with thin collateral → read estimatedLiquidationPrice → expect 0 < value < entry', 'short 1 → expect value > entry'],
    expected: 'Correct side of entry' }),

  // ------------------------------------------------------------ 06 price
  c({ key: 'px.mark.initial', module: '06. Price', fn: 'getMarkPrice', priority: H,
    title: 'Mark equals index until the first fill',
    purpose: 'No trade, no basis',
    steps: ['on a fresh market read getMarkPrice(m) → expect == getIndexPrice(m)'],
    expected: 'Equal' }),
  c({ key: 'px.mark.clamp', module: '06. Price', fn: 'getMarkPrice', priority: H,
    title: 'Mark is the last fill clamped to index ± maxBasis',
    purpose: 'A single trade cannot drag the mark arbitrarily far from the index',
    steps: ['fill at index × 1.008 → read getMarkPrice → expect index × 1.008', 'setMockPrice(index × 0.96) → read getMarkPrice → expect newIndex × 1.01 (the clamp)'],
    expected: 'Inside the band: last fill; outside: the band edge' }),
  c({ key: 'px.band', module: '06. Price', fn: 'placeOrder', priority: H,
    title: 'Limit prices outside index ± band are refused on both sides, and the edge is accepted',
    purpose: 'Fat-finger protection; the boundary must be inclusive',
    steps: ['place Limit buy at lower − 1 tick → expect revert PriceOutOfBand(p, lower, upper)', 'place Limit sell at upper + 1 tick → expect revert', 'place Limit buy at exactly lower → expect success'],
    expected: 'Outside refused, edge accepted' }),
  c({ key: 'px.mock.permissionless', module: '06. Price', fn: 'OracleRouter.setMockPrice', priority: H,
    title: 'Anyone can set the mock index until the market is locked',
    purpose: 'A scenario must be able to drive price without an admin key',
    steps: ['setMockPrice(m, p) from a non-admin → read getIndexPrice → expect p'],
    expected: 'Accepted from any caller' }),
  c({ key: 'px.mock.lock', module: '06. Price', fn: 'OracleRouter.lockMock', priority: H,
    title: 'Locking the mock is admin-only and one-way; the admin feed still works',
    purpose: 'The switch a real deployment flips, and it must not flip back',
    steps: ['lockMock(m) from non-admin → expect revert NotAdmin', 'lockMock(m) from admin → setMockPrice from anyone → expect revert MockIsLocked(m)', 'setPrice(m, p) from admin → expect getIndexPrice == p', 'expect no unlock function in the ABI'],
    expected: 'Locked forever for the mock; admin feed unaffected' }),
  c({ key: 'px.stale', module: '06. Price', fn: 'OracleRouter.getIndexPrice', priority: H,
    title: 'A reading older than maxAge reverts OracleStale; exactly maxAge is fresh',
    purpose: 'Staleness boundary is inclusive',
    steps: ['setMockReading(m, p, now − maxAge − 1) → getIndexPrice → expect revert OracleStale(m, t, maxAge); peek → isStale true', 'setMockReading(m, p, now − maxAge) → getIndexPrice → expect p'],
    expected: 'Boundary inclusive' }),

  // ------------------------------------------------------------ 07 funding
  c({ key: 'fund.permissionless', module: '07. Funding', fn: 'updateFunding', priority: H,
    title: 'updateFunding is permissionless and a no-op inside the interval',
    purpose: 'Keeper role; must not advance early',
    steps: ['call updateFunding(m) from a stranger inside the interval → expect return false; getFundingRate → rate 0, index 0'],
    expected: 'Accepted, no advance' }),
  c({ key: 'fund.boundary', module: '07. Funding', fn: 'updateFunding', priority: H,
    title: 'lastFundingTime always lands on an interval boundary',
    purpose: 'The contract computes the boundary, not the call time',
    steps: ['warp to boundary + 1234 s → updateFunding → read getFundingRate.lastFundingTime → expect % interval == 0 and == now − now % interval'],
    expected: 'Aligned' }),
  c({ key: 'fund.direction', module: '07. Funding', fn: 'updateFunding', priority: H,
    title: 'A positive premium makes longs pay and shorts receive',
    purpose: 'Sign convention',
    pre: 'Mark above index after a fill',
    steps: ['warp one interval → updateFunding → read rate → expect > 0', 'touch both positions → long balance delta < 0, short balance delta > 0 (net of fees)'],
    expected: 'Longs pay' }),
  c({ key: 'fund.cap', module: '07. Funding', fn: 'FundingMath.rateBps', priority: H,
    title: 'The rate is clamped to ± fundingRateCapBps',
    purpose: 'A wild premium must not produce a ruinous rate',
    steps: ['rateBps(500, 1, 75) → 75; rateBps(−500, 1, 75) → −75; rateBps(30, 1, 75) → 30'],
    expected: 'Clamped both ways' }),
  c({ key: 'fund.average', module: '07. Funding', fn: 'FundingMath', priority: M,
    title: 'The rate is the average of premium samples',
    purpose: 'TWAP, not last sample',
    steps: ['samples +10, +20, +30 → rateBps → 20', 'premiumBps(2525, 2500) → 100; premiumBps(2475, 2500) → −100'],
    expected: 'Average and sign correct' }),
  c({ key: 'fund.equity', module: '07. Funding', fn: 'equity', priority: H,
    title: 'Funding owed reduces equity before it is settled',
    purpose: 'Owed funding is a liability now, not when the position is touched',
    steps: ['long with premium → warp → updateFunding → read equity → expect lower than before, with no fill on the account'],
    expected: 'Equity reflects owed funding immediately' }),

  // ------------------------------------------------------------ 08 liquidation
  c({ key: 'liq.above', module: '08. Liquidation', fn: 'liquidate', priority: H,
    title: 'An account above maintenance cannot be liquidated',
    purpose: 'The negative case',
    steps: ['isLiquidatable(a) → false', 'liquidate(a, m) → expect revert NotLiquidatable(a)'],
    expected: 'Revert' }),
  c({ key: 'liq.exact', module: '08. Liquidation', fn: 'isLiquidatable / liquidate', priority: H,
    title: 'The threshold is exact: no buffer on either side',
    purpose: 'isLiquidatable and liquidate must flip at the same tick',
    steps: ['walk the index down $0.10 at a time; at each step: if !isLiquidatable → liquidate reverts NotLiquidatable; at the first true → equity < maintenance and liquidate succeeds'],
    expected: 'Flag and function agree at every tick' }),
  c({ key: 'liq.partial', module: '08. Liquidation', fn: 'liquidate', priority: H,
    title: 'Liquidation closes partialLiquidationBps of the position and pays the liquidator',
    purpose: 'Partial, not full, while the account stays solvent',
    steps: ['liquidate(a, m) → read getPosition.size → expect half', 'read liquidator balance delta → expect liquidationFeeBps × closed notional', 'read getAccount(a) → liquidationCount 1, lastLiquidatedAt == now'],
    expected: 'Half closed; fee paid; account flagged' }),
  c({ key: 'liq.dust', module: '08. Liquidation', fn: 'liquidate',
    title: 'A remainder below minNotional is closed in full',
    purpose: 'No dust positions',
    steps: ['position whose half would be < minNotional → liquidate → read size → expect 0'],
    expected: 'Full close' }),
  c({ key: 'liq.insurance', module: '08. Liquidation', fn: 'liquidate', priority: H,
    title: 'Bad debt is covered by the insurance fund',
    purpose: 'The fund exists for this',
    steps: ['crash the index far past the collateral → liquidate → read vault.balanceOf(a) → expect ≥ 0; insurance balance decreased by the deficit', 'expect event Liquidated with badDebt > 0 and insuranceUsed == badDebt'],
    expected: 'Account restored to zero from the fund' }),
  c({ key: 'liq.fullclose', module: '08. Liquidation', fn: 'liquidate', priority: H,
    title: 'Once the balance is negative the rest of the position is closed in the same call',
    purpose: 'Otherwise the counterparties deleveraged in this round are gone when the next round needs them',
    steps: ['crash deep → single liquidate → read getPosition.size → expect 0; liquidationCount 1'],
    expected: 'One call, whole position' }),
  c({ key: 'liq.paused', module: '08. Liquidation', fn: 'liquidate',
    title: 'A paused exchange blocks liquidation',
    purpose: 'Pause is total',
    steps: ['setPaused(true) → liquidate → expect revert ExchangePaused()'],
    expected: 'Revert' }),
  c({ key: 'liq.flag', module: '08. Liquidation', fn: 'getAccount', priority: H,
    title: 'The liquidation flag is visible through a getter',
    purpose: 'A liquidated account must be identifiable; hidden state is the trap',
    steps: ['read getAccount(a).liquidationCount before → 0; after a liquidation → 1; lastLiquidatedAt == that block'],
    expected: 'Exposed, not hidden' }),

  // ------------------------------------------------------------ 09 ADL
  c({ key: 'adl.trigger', module: '09. Auto-deleveraging', fn: '_autoDeleverage', priority: H,
    title: 'ADL fires only when the insurance fund cannot cover the deficit',
    purpose: 'ADL is the last resort',
    pre: 'Insurance fund drained; a profitable short opposite the bankrupt long',
    steps: ['liquidate(bankrupt) → expect event AutoDeleveraged(short holder); short position 0; bankrupt balance ≥ 0'],
    expected: 'Counterparty closed; deficit socialised' }),
  c({ key: 'adl.notrigger', module: '09. Auto-deleveraging', fn: '_autoDeleverage', priority: H,
    title: 'ADL does not fire while the fund can pay',
    purpose: 'Profitable traders are untouched when the fund suffices',
    pre: 'Insurance fund funded',
    steps: ['liquidate(bankrupt) → expect no AutoDeleveraged event; short holder position unchanged'],
    expected: 'No ADL' }),
  c({ key: 'adl.rank', module: '09. Auto-deleveraging', fn: '_autoDeleverage',
    title: 'ADL picks the most profitable, largest opposite position first',
    purpose: 'Ranking rule',
    pre: 'Two shorts: one large in profit, one small',
    steps: ['liquidate(bankrupt) with a deficit the large short covers alone → expect only the large short closed'],
    expected: 'Highest score first; stops when covered' }),

  // ------------------------------------------------------------ 10 fees
  c({ key: 'fee.taker', module: '10. Fees', fn: '_fill', priority: H,
    title: 'The taker pays takerFeeBps of notional',
    purpose: 'Fee arithmetic',
    steps: ['taker fills 2501 notional at 5 bps → balance delta −1.2505e6 (plus pnl if any)'],
    expected: 'Exact bps' }),
  c({ key: 'fee.rebate', module: '10. Fees', fn: '_fill', priority: H,
    title: 'A negative maker fee is a rebate credited to the maker',
    purpose: 'Maker incentive',
    steps: ['maker with −2 bps on 2501 notional → balance delta +0.5002e6'],
    expected: 'Credited' }),
  c({ key: 'fee.split', module: '10. Fees', fn: '_fill', priority: H,
    title: 'Net fee is split between treasury and insurance by feeToInsuranceBps',
    purpose: 'Where the money goes',
    steps: ['taker 1.25, rebate 0.50 → net 0.75 at 50 % → treasury +0.375e6, insurance +0.375e6'],
    expected: 'Split exact' }),
  c({ key: 'fee.set', module: '10. Fees', fn: 'setFees',
    title: 'setFees applies to the next fill',
    purpose: 'Admin fee change is live immediately',
    steps: ['setFees(m, 0, 10) → market buy 1 → balance delta −10 bps of notional'],
    expected: 'New rate applied' }),

  // ------------------------------------------------------------ 11 admin
  c({ key: 'adm.strangers', module: '11. Admin', fn: 'onlyAdmin', priority: H,
    title: 'Every admin function rejects a non-admin',
    purpose: 'Closed surface',
    steps: ['from a stranger call setPaused, setMarketStatus, setFees, transferAdmin, addMarket, setMarketParams → each expect revert NotAdmin()'],
    expected: 'All revert' }),
  c({ key: 'adm.transfer', module: '11. Admin', fn: 'transferAdmin / acceptAdmin', priority: H,
    title: 'Admin handover is two-step and only the pending admin can accept',
    purpose: 'A typo in the new address must not lose the key',
    steps: ['transferAdmin(new) → read admin → unchanged; pendingAdmin → new', 'acceptAdmin from a stranger → expect revert PendingAdminMismatch()', 'acceptAdmin from new → admin == new; pendingAdmin == 0', 'old admin calls setPaused → expect revert NotAdmin'],
    expected: 'Two steps; old key dead after' }),
  c({ key: 'adm.accept.none', module: '11. Admin', fn: 'acceptAdmin', priority: H,
    title: 'acceptAdmin with nothing pending reverts',
    purpose: 'pendingAdmin == 0 is "nothing to accept", not "anyone may accept"',
    steps: ['acceptAdmin from any address with pendingAdmin == 0 → expect revert PendingAdminMismatch()'],
    expected: 'Revert' }),
  c({ key: 'adm.pause', module: '11. Admin', fn: 'setPaused', priority: H,
    title: 'Pause blocks orders and triggers but not cancels or withdrawals',
    purpose: 'Users must always be able to reduce exposure to the venue',
    steps: ['setPaused(true) → placeOrder → revert ExchangePaused; triggerOrder → revert ExchangePaused', 'cancelOrder → success; withdraw → success', 'setPaused(false) → placeOrder → success'],
    expected: 'Exactly the mutating-risk paths are blocked' }),
  c({ key: 'adm.pause.order', module: '11. Admin', fn: 'placeOrder', priority: H,
    title: 'ExchangePaused is checked before AccountNotFound',
    purpose: 'Gate order, first pair',
    steps: ['setPaused(true) → placeOrder from an address with no account → expect revert ExchangePaused, not AccountNotFound'],
    expected: 'Pause wins' }),
  c({ key: 'adm.status.order', module: '11. Admin', fn: 'placeOrder', priority: H,
    title: 'AccountNotFound is checked before MarketPaused',
    purpose: 'Gate order, second pair',
    steps: ['setMarketStatus(m, Paused) → placeOrder from an address with no account → expect revert AccountNotFound, not MarketPaused'],
    expected: 'Account wins' }),
  c({ key: 'adm.params.set', module: '11. Admin', fn: 'setMarketParams',
    title: 'setMarketParams replaces the parameter set and is validated like addMarket',
    purpose: 'Live retuning with the same guard rails',
    steps: ['setMarketParams(m, valid) → getMarketParams == valid; event MarketParamsSet', 'setMarketParams(m, invalid) → revert BadParams'],
    expected: 'Applied or refused with reason' }),

  // ------------------------------------------------------------ 12 events
  c({ key: 'ev.placed', module: '12. Events', fn: 'OrderPlaced', priority: H,
    title: 'OrderPlaced carries every order parameter',
    purpose: 'The indexer rebuilds orders from this event alone',
    steps: ['placeOrder → decode OrderPlaced → expect orderId, owner, marketId (indexed), side, type, tif, size, price, triggerPrice, reduceOnly, userOrderId, maxTs all equal to the params'],
    expected: 'Field-for-field' }),
  c({ key: 'ev.filled', module: '12. Events', fn: 'OrderFilled', priority: H,
    title: 'OrderFilled names the maker, and zero for the backstop',
    purpose: 'A reader distinguishes trader liquidity from venue liquidity by this field',
    steps: ['market buy 2 with 1 resting from bob → expect two OrderFilled: maker bob then maker 0x0; makerOrderId set then 0'],
    expected: 'Maker address zero ⇔ backstop' }),
  c({ key: 'ev.cancelled', module: '12. Events', fn: 'OrderCancelled',
    title: 'OrderCancelled carries the unfilled size and a reason',
    purpose: 'Reasons: user, cancelall, ioc, unfilled, fok, postonly, margin, reduceonly',
    steps: ['cancel a half-filled order → expect unfilled == size − filled, reason "user"', 'IOC remainder → reason "ioc"; market remainder → "unfilled"'],
    expected: 'Reason matches the path' }),
  c({ key: 'ev.position', module: '12. Events', fn: 'PositionChanged', priority: H,
    title: 'PositionChanged reports before/after size, entry, realised delta and funding paid',
    purpose: 'One event per side per fill is what the positions table is built from',
    steps: ['fill → expect PositionChanged for taker and maker with sizeBefore/sizeAfter consistent with getPosition'],
    expected: 'Two events per fill, consistent with state' }),
  c({ key: 'ev.funding', module: '12. Events', fn: 'FundingUpdated',
    title: 'FundingUpdated reports rate, cumulative index, boundary time and sample count',
    purpose: 'Funding history is rebuilt from this',
    steps: ['updateFunding across a boundary → expect FundingUpdated(m, rate, index, boundaryTime, samples ≥ 1)'],
    expected: 'All fields set' }),
  c({ key: 'ev.liquidated', module: '12. Events', fn: 'Liquidated', priority: H,
    title: 'Liquidated reports size, price, fee, bad debt and insurance used',
    purpose: 'The liquidations table and the insurance accounting come from here',
    steps: ['liquidate → expect Liquidated(account, m, liquidator, sizeClosed, mark, fee, badDebt, insuranceUsed) with insuranceUsed ≤ badDebt'],
    expected: 'Fields consistent with balances' }),
];

// ------------------------------------------------------------ 13 parameterised over markets
for (const m of MARKETS) {
  const mod = '13. Per-market';
  cases.push(
    c({ key: `pm.${m.sym}.step`, module: mod, fn: 'placeOrder', priority: H,
      title: `${m.sym}: size off the step is refused (step ${m.step})`,
      purpose: 'Step is per market; a value that is valid on one market must be refused on another',
      steps: [`place size = step + 1 unit on market ${m.id} → expect revert InvalidStep(size, step)`],
      expected: 'Revert with the market\'s own step' }),
    c({ key: `pm.${m.sym}.tick`, module: mod, fn: 'placeOrder', priority: H,
      title: `${m.sym}: price off the tick is refused (tick ${m.tick})`,
      purpose: 'Tick is per market',
      steps: [`place Limit at price = tick multiple + 1 unit on market ${m.id} → expect revert InvalidTick(price, tick)`],
      expected: 'Revert with the market\'s own tick' }),
    c({ key: `pm.${m.sym}.band`, module: mod, fn: 'placeOrder', priority: H,
      title: `${m.sym}: the price band is index ± 5 % around ${m.index}`,
      purpose: 'Band bounds derive from each market\'s index',
      steps: [`compute lower/upper from getIndexPrice(${m.id}) → place at lower − tick → revert PriceOutOfBand(p, lower, upper); place at lower → success`],
      expected: 'Bounds computed from this market\'s index' }),
    c({ key: `pm.${m.sym}.minnotional`, module: mod, fn: 'placeOrder', priority: M,
      title: `${m.sym}: notional below $${m.minNotional} is refused`,
      purpose: 'Min notional is evaluated at the limit price or the index',
      steps: [`place the smallest step size whose notional < ${m.minNotional} → expect revert BelowMinNotional(n, min)`],
      expected: 'Revert with the computed notional' }),
    c({ key: `pm.${m.sym}.margin`, module: mod, fn: 'placeOrder', priority: H,
      title: `${m.sym}: initial margin is ${m.im} of notional`,
      purpose: 'IM differs per market; the InsufficientCollateral error must report the market\'s requirement',
      steps: [`fund exactly IM − 1 unit; place 1 unit at index → expect revert InsufficientCollateral(free, required) with required == notional × IM`],
      expected: 'Required equals this market\'s IM' }),
    c({ key: `pm.${m.sym}.liq.low`, module: mod, fn: 'liquidate', priority: H,
      title: `${m.sym}: liquidation at 2x leverage happens far from entry`,
      purpose: 'Maintenance ${m.mm}: at 2x the price must fall ~half before liquidation',
      steps: [`open 1 unit with collateral = 50 % of notional; walk the index down; record the first liquidatable index → expect drop ≈ (50 % − MM) of entry`],
      expected: 'Threshold matches equity == MM arithmetic' }),
    c({ key: `pm.${m.sym}.liq.mid`, module: mod, fn: 'liquidate', priority: H,
      title: `${m.sym}: liquidation at 10x leverage`,
      purpose: 'Same rule, 10 % collateral',
      steps: ['open 1 unit with collateral = 10 % of notional; walk the index down; first liquidatable index → expect drop ≈ (10 % − MM) of entry'],
      expected: 'Threshold matches' }),
    c({ key: `pm.${m.sym}.liq.max`, module: mod, fn: 'liquidate', priority: H,
      title: `${m.sym}: liquidation at max leverage (${m.lev}x)`,
      purpose: 'Thinnest allowed collateral: liquidation is one small move away',
      steps: [`open 1 unit with collateral = IM exactly; walk the index down → expect liquidatable within (IM − MM) of entry`],
      expected: 'Threshold matches' }),
    c({ key: `pm.${m.sym}.fund.pos`, module: mod, fn: 'updateFunding', priority: M,
      title: `${m.sym}: positive premium → positive rate, longs pay`,
      purpose: 'Funding sign per market',
      steps: [`fill above index on market ${m.id}; warp one interval; updateFunding → rate > 0; long balance decreases on next touch`],
      expected: 'Rate > 0, longs pay' }),
    c({ key: `pm.${m.sym}.fund.neg`, module: mod, fn: 'updateFunding', priority: M,
      title: `${m.sym}: negative premium → negative rate, shorts pay`,
      purpose: 'Funding sign per market, other direction',
      steps: [`fill below index on market ${m.id}; warp one interval; updateFunding → rate < 0; short balance decreases on next touch`],
      expected: 'Rate < 0, shorts pay' }),
  );
}

module.exports = { cases, MARKETS };
